In [1]:
import pandas as pd

# 데이터 로딩
orders = pd.read_csv("orders.csv")
prior = pd.read_csv("order_products__prior.csv")
train = pd.read_csv("order_products__train.csv")
products = pd.read_csv("products.csv")
aisles = pd.read_csv("aisles.csv")
departments = pd.read_csv("departments.csv")

## 데이터 통합

In [2]:
# prior, train 주문 통합
order_products = pd.concat([prior, train], axis=0)

In [3]:
# 주문 정보 병합: order_id 기준
orders_sub = orders[["order_id", "user_id", "order_number", "order_hour_of_day", "days_since_prior_order", "eval_set"]]
df = order_products.merge(orders_sub, on="order_id", how="left")
df

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,order_hour_of_day,days_since_prior_order,eval_set
0,2,33120,1,1,202279,3,9,8.0,prior
1,2,28985,2,1,202279,3,9,8.0,prior
2,2,9327,3,0,202279,3,9,8.0,prior
3,2,45918,4,1,202279,3,9,8.0,prior
4,2,30035,5,0,202279,3,9,8.0,prior
...,...,...,...,...,...,...,...,...,...
33819101,3421063,14233,3,1,169679,30,10,4.0,train
33819102,3421063,35548,4,1,169679,30,10,4.0,train
33819103,3421070,35951,1,1,139822,15,10,8.0,train
33819104,3421070,16953,2,1,139822,15,10,8.0,train
33819105,3421070,4724,3,1,139822,15,10,8.0,train

In [4]:
# 상품 → aisle, department 정보 추가
df = df.merge(products, on="product_id", how="left")
df

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,order_hour_of_day,days_since_prior_order,eval_set,product_name,aisle_id,department_id
0,2,33120,1,1,202279,3,9,8.0,prior,Organic Egg Whites,86,16
1,2,28985,2,1,202279,3,9,8.0,prior,Michigan Organic Kale,83,4
2,2,9327,3,0,202279,3,9,8.0,prior,Garlic Powder,104,13
3,2,45918,4,1,202279,3,9,8.0,prior,Coconut Butter,19,13
4,2,30035,5,0,202279,3,9,8.0,prior,Natural Sweetener,17,13
...,...,...,...,...,...,...,...,...,...,...,...,...
33819101,3421063,14233,3,1,169679,30,10,4.0,train,Natural Artesian Water,115,7
33819102,3421063,35548,4,1,169679,30,10,4.0,train,Twice Baked Potatoes,13,20
33819103,3421070,35951,1,1,139822,15,10,8.0,train,Organic Unsweetened Almond Milk,91,16
33819104,3421070,16953,2,1,139822,15,10,8.0,train,Creamy Peanut Butter,88,13
33819105,3421070,4724,3,1,139822,15,10,8.0,train,Broccoli Florettes,32,4

In [5]:
# 상품 → aisle, department 정보 추가
df = df.merge(aisles, on="aisle_id", how="left")
df

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,order_hour_of_day,days_since_prior_order,eval_set,product_name,aisle_id,department_id,aisle
0,2,33120,1,1,202279,3,9,8.0,prior,Organic Egg Whites,86,16,eggs
1,2,28985,2,1,202279,3,9,8.0,prior,Michigan Organic Kale,83,4,fresh vegetables
2,2,9327,3,0,202279,3,9,8.0,prior,Garlic Powder,104,13,spices seasonings
3,2,45918,4,1,202279,3,9,8.0,prior,Coconut Butter,19,13,oils vinegars
4,2,30035,5,0,202279,3,9,8.0,prior,Natural Sweetener,17,13,baking ingredients
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33819101,3421063,14233,3,1,169679,30,10,4.0,train,Natural Artesian Water,115,7,water seltzer sparkling water
33819102,3421063,35548,4,1,169679,30,10,4.0,train,Twice Baked Potatoes,13,20,prepared meals
33819103,3421070,35951,1,1,139822,15,10,8.0,train,Organic Unsweetened Almond Milk,91,16,soy lactosefree
33819104,3421070,16953,2,1,139822,15,10,8.0,train,Creamy Peanut Butter,88,13,spreads
33819105,3421070,4724,3,1,139822,15,10,8.0,train,Broccoli Florettes,32,4,packaged produce

In [6]:
# 상품 → aisle, department 정보 추가
df = df.merge(departments, on="department_id", how="left")
df

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,order_hour_of_day,days_since_prior_order,eval_set,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,202279,3,9,8.0,prior,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,202279,3,9,8.0,prior,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,202279,3,9,8.0,prior,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,202279,3,9,8.0,prior,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,202279,3,9,8.0,prior,Natural Sweetener,17,13,baking ingredients,pantry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33819101,3421063,14233,3,1,169679,30,10,4.0,train,Natural Artesian Water,115,7,water seltzer sparkling water,beverages
33819102,3421063,35548,4,1,169679,30,10,4.0,train,Twice Baked Potatoes,13,20,prepared meals,deli
33819103,3421070,35951,1,1,139822,15,10,8.0,train,Organic Unsweetened Almond Milk,91,16,soy lactosefree,dairy eggs
33819104,3421070,16953,2,1,139822,15,10,8.0,train,Creamy Peanut Butter,88,13,spreads,pantry
33819105,3421070,4724,3,1,139822,15,10,8.0,train,Broccoli Florettes,32,4,packaged produce,produce

## df 정렬 및 분석

In [7]:
df = df[[
    "user_id",
    "eval_set",

    "order_id",
    "order_number",
    "order_hour_of_day",
    "days_since_prior_order",

    "product_id",
    "product_name",
    "add_to_cart_order",
    "reordered",

    "aisle_id",
    "aisle",
    "department_id",
    "department"
]]

df.head()

,user_id,eval_set,order_id,order_number,order_hour_of_day,days_since_prior_order,product_id,product_name,add_to_cart_order,reordered,aisle_id,aisle,department_id,department
0,202279,prior,2,3,9,8.0,33120,Organic Egg Whites,1,1,86,eggs,16,dairy eggs
1,202279,prior,2,3,9,8.0,28985,Michigan Organic Kale,2,1,83,fresh vegetables,4,produce
2,202279,prior,2,3,9,8.0,9327,Garlic Powder,3,0,104,spices seasonings,13,pantry
3,202279,prior,2,3,9,8.0,45918,Coconut Butter,4,1,19,oils vinegars,13,pantry
4,202279,prior,2,3,9,8.0,30035,Natural Sweetener,5,0,17,baking ingredients,13,pantry

In [ ]:
# test는 order_products_prior과 train에 없었기 대문에 병합시 자동 삭제됨 
df[df['eval_set']=='test'].head()

Empty DataFrame
Columns: [user_id, eval_set, order_id, order_number, order_hour_of_day, days_since_prior_order, product_id, product_name, add_to_cart_order, reordered, aisle_id, aisle, department_id, department]
Index: []

In [12]:
df = df.sort_values(by=["user_id", "order_number", "add_to_cart_order"]).reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33819106 entries, 0 to 33819105
Data columns (total 14 columns):
 #   Column                  Dtype
---  ------                  -----
 0   user_id                 int64
 1   eval_set                object
 2   order_id                int64
 3   order_number            int64
 4   order_hour_of_day       int64
 5   days_since_prior_order  float64
 6   product_id              int64
 7   product_name            object
 8   add_to_cart_order       int64
 9   reordered               int64
 10  aisle_id                int64
 11  aisle                   object
 12  department_id           int64
 13  department              object
dtypes: float64(1), int64(9), object(4)
memory usage: 3.5+ GB

In [15]:
df.isnull().sum()

user_id                         0
eval_set                        0
order_id                        0
order_number                    0
order_hour_of_day               0
days_since_prior_order    2078068
product_id                      0
product_name                    0
add_to_cart_order               0
reordered                       0
aisle_id                        0
aisle                           0
department_id                   0
department                      0
is_last_order                   0
dtype: int64

## days_since_prior_order는 첫주문시 None이 맞음

In [16]:
# 'days_since_prior_order' 컬럼이 NaN인 행만 필터링
nan_days_since_prior_order_rows = df[df['days_since_prior_order'].isna()]

# 필터링된 행들의 'order_number' 값 확인
# 고유한 order_number 값들을 출력하여 1 외의 값이 있는지 확인합니다.
unique_order_numbers_with_nan = nan_days_since_prior_order_rows['order_number'].unique()

unique_order_numbers_with_nan

array([1])

## test 라벨링

In [13]:
# 1. 유저별 마지막 order_number 계산
user_max_order = df.groupby("user_id")["order_number"].max().reset_index()
user_max_order.columns = ["user_id", "max_order_number"]

# 2. 병합해서 각 row가 마지막 주문인지 표시
df = df.merge(user_max_order, on="user_id", how="left")
df["is_last_order"] = df["order_number"] == df["max_order_number"]

# 3. 마지막 주문이면서 eval_set이 prior이면 → test로 변경
df.loc[(df["eval_set"] == "prior") & (df["is_last_order"]), "eval_set"] = "test"

# 4. 중간 컬럼 제거
df.drop(columns=["max_order_number"], inplace=True)

df

,user_id,eval_set,order_id,order_number,order_hour_of_day,days_since_prior_order,product_id,product_name,add_to_cart_order,reordered,aisle_id,aisle,department_id,department,is_last_order
0,1,prior,2539329,1,8,NaN,196,Soda,1,0,77,soft drinks,7,beverages,False
1,1,prior,2539329,1,8,NaN,14084,Organic Unsweetened Vanilla Almond Milk,2,0,91,soy lactosefree,16,dairy eggs,False
2,1,prior,2539329,1,8,NaN,12427,Original Beef Jerky,3,0,23,popcorn jerky,19,snacks,False
3,1,prior,2539329,1,8,NaN,26088,Aged White Cheddar Popcorn,4,0,23,popcorn jerky,19,snacks,False
4,1,prior,2539329,1,8,NaN,26405,XL Pick-A-Size Paper Towel Rolls,5,0,54,paper goods,17,household,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33819101,206209,train,272231,14,14,30.0,40603,Fabric Softener Sheets,4,0,75,laundry,17,household,True
33819102,206209,train,272231,14,14,30.0,15655,Dark Chocolate Mint Snacking Chocolate,5,0,45,candy chocolate,19,snacks,True
33819103,206209,train,272231,14,14,30.0,42606,Phish Food Frozen Yogurt,6,0,37,ice cream ice,1,frozen,True
33819104,206209,train,272231,14,14,30.0,37966,French Baguette Bread,7,0,112,bread,3,bakery,True
33819105,206209,train,272231,14,14,30.0,39216,Original Multigrain Spoonfuls Cereal,8,1,121,cereal,14,breakfast,True

## 최종 출력 확인 및 저장

In [ ]:
df[df['eval_set']=='test']
# 전체 데이터: 780800

,user_id,eval_set,order_id,order_number,order_hour_of_day,days_since_prior_order,product_id,product_name,add_to_cart_order,reordered,aisle_id,aisle,department_id,department,is_last_order
378,3,test,1402502,12,15,15.0,39190,Vanilla Unsweetened Almond Milk,1,1,91,soy lactosefree,16,dairy eggs,True
379,3,test,1402502,12,15,15.0,18599,Garlic Couscous,2,1,4,instant foods,9,dry goods pasta,True
380,3,test,1402502,12,15,15.0,23650,Electrolyte Water,3,1,115,water seltzer sparkling water,7,beverages,True
381,3,test,1402502,12,15,15.0,21903,Organic Baby Spinach,4,1,123,packaged vegetables fruits,4,produce,True
382,3,test,1402502,12,15,15.0,47766,Organic Avocado,5,1,24,fresh fruits,4,produce,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33818964,206208,test,1882108,49,22,7.0,2643,Organic Bagged Kale Salad Mix,13,1,123,packaged vegetables fruits,4,produce,True
33818965,206208,test,1882108,49,22,7.0,21405,"Organic Red Radish, Bunch",14,0,83,fresh vegetables,4,produce,True
33818966,206208,test,1882108,49,22,7.0,7632,Old Style Whole Grain Dijon Mustard,15,0,72,condiments,13,pantry,True
33818967,206208,test,1882108,49,22,7.0,1942,Aged White Wine Vinegar,16,0,19,oils vinegars,13,pantry,True
33818968,206208,test,1882108,49,22,7.0,10385,Organic English Cucumber,17,1,83,fresh vegetables,4,produce,True

In [ ]:
df[df['eval_set']=='train']
# 전체 데이터 1384617

,user_id,eval_set,order_id,order_number,order_hour_of_day,days_since_prior_order,product_id,product_name,add_to_cart_order,reordered,aisle_id,aisle,department_id,department,is_last_order
59,1,train,1187899,11,8,14.0,196,Soda,1,1,77,soft drinks,7,beverages,True
60,1,train,1187899,11,8,14.0,25133,Organic String Cheese,2,1,21,packaged cheese,16,dairy eggs,True
61,1,train,1187899,11,8,14.0,38928,0% Greek Strained Yogurt,3,1,120,yogurt,16,dairy eggs,True
62,1,train,1187899,11,8,14.0,26405,XL Pick-A-Size Paper Towel Rolls,4,1,54,paper goods,17,household,True
63,1,train,1187899,11,8,14.0,39657,Milk Chocolate Almonds,5,1,45,candy chocolate,19,snacks,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33819101,206209,train,272231,14,14,30.0,40603,Fabric Softener Sheets,4,0,75,laundry,17,household,True
33819102,206209,train,272231,14,14,30.0,15655,Dark Chocolate Mint Snacking Chocolate,5,0,45,candy chocolate,19,snacks,True
33819103,206209,train,272231,14,14,30.0,42606,Phish Food Frozen Yogurt,6,0,37,ice cream ice,1,frozen,True
33819104,206209,train,272231,14,14,30.0,37966,French Baguette Bread,7,0,112,bread,3,bakery,True
33819105,206209,train,272231,14,14,30.0,39216,Original Multigrain Spoonfuls Cereal,8,1,121,cereal,14,breakfast,True

In [ ]:
df
# 전체 데이터 33819106

,user_id,eval_set,order_id,order_number,order_hour_of_day,days_since_prior_order,product_id,product_name,add_to_cart_order,reordered,aisle_id,aisle,department_id,department,is_last_order
0,1,prior,2539329,1,8,NaN,196,Soda,1,0,77,soft drinks,7,beverages,False
1,1,prior,2539329,1,8,NaN,14084,Organic Unsweetened Vanilla Almond Milk,2,0,91,soy lactosefree,16,dairy eggs,False
2,1,prior,2539329,1,8,NaN,12427,Original Beef Jerky,3,0,23,popcorn jerky,19,snacks,False
3,1,prior,2539329,1,8,NaN,26088,Aged White Cheddar Popcorn,4,0,23,popcorn jerky,19,snacks,False
4,1,prior,2539329,1,8,NaN,26405,XL Pick-A-Size Paper Towel Rolls,5,0,54,paper goods,17,household,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33819101,206209,train,272231,14,14,30.0,40603,Fabric Softener Sheets,4,0,75,laundry,17,household,True
33819102,206209,train,272231,14,14,30.0,15655,Dark Chocolate Mint Snacking Chocolate,5,0,45,candy chocolate,19,snacks,True
33819103,206209,train,272231,14,14,30.0,42606,Phish Food Frozen Yogurt,6,0,37,ice cream ice,1,frozen,True
33819104,206209,train,272231,14,14,30.0,37966,French Baguette Bread,7,0,112,bread,3,bakery,True
33819105,206209,train,272231,14,14,30.0,39216,Original Multigrain Spoonfuls Cereal,8,1,121,cereal,14,breakfast,True

In [20]:
df.to_csv('master_dataset.csv', index=False)